name: nexux
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.4.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  geolocator: ^14.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  cloud_firestore: ^5.6.11
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/pizza.png
    - assets/images/burger.png
    - assets/images/sushi.png
    - assets/images/wrap.png
    - assets/images/pasta.png
    - assets/images/coffee.png
    - assets/images/tandoori.png
    - assets/images/brownie.png